steps:
  # 1. Build Backend API Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/api:latest', '-f', 'docker/Dockerfile.api', '.']

  # 2. Build Worker Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/worker:latest', '-f', 'docker/Dockerfile.worker', '.']

  # 3. Build Next.js Frontend Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/frontend:latest'
      - '-f'
      - 'docker/Dockerfile.frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyD9TG-5X7_Lksyt_Kv5fwXMkXu9rSfF0DM'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=auto-job-apply-1859b.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=auto-job-apply-1859b'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=auto-job-apply-1859b.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=831721132982'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:831721132982:web:1d6d8b4640587c3c9ae717'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://auto-job-apply-api-831721132982.us-central1.run.app'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/api:latest'
  - 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/worker:latest'
  - 'us-central1-docker.pkg.dev/auto-job-apply-1859b/auto-job-apply/frontend:latest'

