"""add pipeline fields to leads

Adds columns the live pipeline (skills/, graph/, orchestrator/) actually
depends on that were missing from the initial schema: source, x_handle,
resume_version (plain filename slug, see db/models.py's Lead docstring),
review_decision, posted_date. Also relaxes leads.company/role to nullable
and adds a per-user unique constraint on x_handle, since X-sourced leads
(skills/scrape_x_leads.py) have no company/role at scrape time.

Note: downgrade() re-tightens company/role to NOT NULL. If any lead rows
have NULL company/role at that point (e.g. real X-sourced leads), the
downgrade will fail with a NOT NULL violation -- that's intentional; it
surfaces the data-loss risk rather than silently deleting/coercing rows.

Revision ID: 2b37dacdefc8
Revises: 68f647841397
Create Date: 2026-08-25 19:20:24.528836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b37dacdefc8'
down_revision: Union[str, None] = '68f647841397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('x_handle', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('resume_version', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('review_decision', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('posted_date', sa.String(), nullable=True))
    op.alter_column('leads', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_leads_user_x_handle', 'leads', ['user_id', 'x_handle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leads_user_x_handle', 'leads', type_='unique')
    op.alter_column('leads', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leads', 'posted_date')
    op.drop_column('leads', 'review_decision')
    op.drop_column('leads', 'resume_version')
    op.drop_column('leads', 'x_handle')
    op.drop_column('leads', 'source')
    # ### end Alembic commands ###
